<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE data [
  <!ELEMENT data (stuff+)>
  <!ELEMENT stuff (name,other*)>
  <!ELEMENT name  (#PCDATA)>
  <!ELEMENT other (#PCDATA)>
]>
<data>
  <stuff>
    <name>Moose</name>
  </stuff>
  <stuff>
    <name>Thingy</name>
    <other>Value</other>
  </stuff>
  <stuff>
    <name>Third</name>
    <other>Value</other>
    <other>Value2</other>
  </stuff>
</data>