<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE data [
  <!ELEMENT data (stuff+)>
  <!ELEMENT stuff (name,empty)>
  <!ELEMENT name  (#PCDATA)>
  <!ELEMENT empty EMPTY>
]>
<data>
  <stuff>
    <name>Moose</name>
    <empty />
  </stuff>
  <stuff>
    <name>Thingy</name>
    <empty />
  </stuff>
</data>