<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE data [
  <!ELEMENT data (stuff+)>
  <!ELEMENT stuff (name,other,optional?,(penultimate?,last?)+)>
  <!ELEMENT name  (#PCDATA)>
  <!ELEMENT other (#PCDATA)>
  <!ELEMENT optional    (#PCDATA)>
  <!ELEMENT penultimate (#PCDATA)>
  <!ELEMENT last        (#PCDATA)>
]>
<data>
  <stuff>
    <name>Moose</name>
    <other>Value</other>
  </stuff>
  <stuff>
    <name>Thingy</name>
    <other>Value2</other>
  </stuff>
</data>